### ISSUE TITLE
Setting MultiValueHeaders causes header duplication

### ISSUE THREAD

**Issue by earthboundkid** [piotrkubisa/apigo#13]
See https://community.netlify.com/t/headers-doubled/16605/14 for a discussion. I'm not sure if it's our fault for adding the MultiValueHeaders or Netlify's fault for not-deduplicating them vs. regular headers.

**Comment by piotrkubisa** [comment]
Hello, I am sorry for delay.

First, if you don't have expertise in Lambda and you also are not looking forward to debugging the issue I'd like to recommend you to switch to the tj's https://github.com/apex/gateway (if you haven't already). Both libraries share a lot of similarities and I suppose it might be more updated recently. 

Personally, I am struggling to find free time, motivation and starting being out-of-date with AWS Lambda and API Gateway interface. I also don't have any service running on AWS/Netlify using this proxy nor intention to deploy anytime soon, which makes harder to reproduce, resolve and push a fix for a certain problem. I don't promise to debug this issue, however I have plans to push some updates soon, if only I would be able to allocate some time for a side-project.

**Comment by earthboundkid** [comment]
No problem. I think I'll just make my own fork for now.
